--ASSIGNMENT 5--
USE DEMO;

SELECT * FROM EMP_1;
SELECT * FROM EMP_SAL;

-- EID NAME CITY DOJ DEPT DESI SALARY OF THE DELHI EMPLOYEES
SELECT EMP_1.EMPID,NAME,CITY,DOJ, DEPT,DESI, SALARY FROM EMP_1
INNER JOIN EMP_SAL 
ON EMP_1.EMPID=EMP_SAL.EID
WHERE CITY='DEL';

--INSERTING NULL VALUES
SELECT * FROM EMP_SAL;
--DELETE FROM EMP_SAL WHERE EID='E0008';
INSERT INTO EMP_SAL(EID,DEPT,DESI, DOJ) VALUES('E0008','Marketing','Manager','01-MAR-2019');

--DETAILS OF ALL THE EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVAILABLE.
SELECT * FROM EMP_1
WHERE EMPID IN(SELECT EID FROM EMP_SAL WHERE SALARY IS NULL);

-- IN THE INVENTORY STRUCTURE DISPLAY

USE INVENTORY;

SELECT * FROM CUST;
SELECT * FROM PRODUCT;
--SELECT * FROM SUPPLIER;
SELECT * FROM ORDERS;
SELECT * FROM STOCK;

--PID, PDESC, CATEGORY, SNAME,SCITY
SELECT PRODUCT.PID,PDESC,CATEGORY,SNAME,SCITY FROM PRODUCT
INNER JOIN SUPPLIER
ON PRODUCT.SID=SUPPLIER.SID;

--DISPLAY OID, ODATE,CNAME,CADDRESS, CPHONE,PDESC, PRICE, OQTY,AMI/T
SELECT ORDERS.OID,ODATE,CNAME,ADDRES,PHONE,PDESC,PRICE,OQTY FROM ORDERS
INNER JOIN CUST
ON ORDERS.CID=CUST.CID
INNER JOIN PRODUCT
ON ORDERS.PID=PRODUCT.PID;


--ASSIGNMENT 6
USE DEMO;

SELECT * FROM EMP_1;
SELECT * FROM EMP_SAL;

--CREATING VIEW FOR EMP_SAL_DETAILS
CREATE VIEW EMP_SAL_DETAILS
AS 
(SELECT EMP_1.EMPID, NAME, DOJ, DEPT,DESI, SALARY AS 'BASIC', SALARY*.15 AS 'HRA', SALARY*.09 AS 'PF', SALARY+(SALARY*.15)+(SALARY*.09) AS 'NET'
,(SALARY+(SALARY*.15)+(SALARY*.09))-SALARY*.09 AS 'GROSS' FROM EMP_1
INNER JOIN EMP_SAL
ON EMP_1.EMPID=EMP_SAL.EID
);

SELECT * FROM EMP_SAL_DETAILS;

--CREATE A VIEW TO DISPLAY EID, NAME, DOJ, DESI, DEPT OF AL THE MANAGERS JOINED IN 2019
CREATE VIEW VIEW_
AS (
SELECT EMP_1.EMPID, NAME,DOJ,DESI,DEPT FROM EMP_1
INNER JOIN EMP_SAL
ON EMP_1.EMPID=EMP_SAL.EID
WHERE YEAR(DOJ)=2019
);

SELECT * FROM VIEW_;

--INVENTORY--
USE INVENTORY;

CREATE VIEW BILL
AS (
SELECT ORDERS.OID,ODATE,CNAME,ADDRES,PHONE,PDESC,PRICE,OQTY FROM ORDERS
INNER JOIN CUST
ON ORDERS.CID=CUST.CID
INNER JOIN PRODUCT
ON ORDERS.PID=PRODUCT.PID
);

SELECT * FROM BILL;   --AMOUNT IS NOT IN TABLE

--ASSIGNMENT 6--

USE DEMO;

SELECT * FROM EMP_1;
SELECT * FROM EMP_SAL;

-- DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF ALL EMPLOYEES.
SELECT DEPT, COUNT(*) AS 'TEAM SIZE',AVG(SALARY) AS 'AVG SALARY' FROM EMP_SAL
GROUP BY DEPT;

--COUNT OF MANAGERS IN THE COMPANY.
SELECT * FROM EMP_SAL --;
WHERE DESI LIKE 'MANAGER';

--MAXIMUM AND MINIMUM SALARY OF AN ASSOCIATE
SELECT MAX(SALARY) AS 'MAXIMUM', MIN(SALARY) AS 'MINIMUM' FROM EMP_SAL;

--DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF DELHI EMPLOYEES 
SELECT DEPT,COUNT(*) AS 'TEAM SIZE',AVG(SALARY) AS 'AVG SALARY' FROM EMP_SAL
WHERE EID IN (SELECT EMPID FROM EMP_1 WHERE CITY='DEL')
GROUP BY DEPT;

--GENERATE OFFICIAL EMAIL OF THE EMPLOYEE TAKIG 1ST CHARACTER OF FIRST NAME, 1SST CHARACTER OF LAST NAME,
--LAST 3 DIGITS OF EID FOLLOWED BY "RCG.COM". EMAIL SHOULD BE IN UPPER CASE

SELECT CONCAT(LEFT(NAME,1),LEFT(RIGHT(NAME,CHARINDEX(' ',NAME)),1),SUBSTRING(EMPID,3,3),'@RCG.COM') AS 'EMAIL'
FROM EMP_1;

--NAME,CITY,PHNO AND EMAIL OF THE EMPLOYEES WHOSE AGE>=40/30/25
SELECT NAME, CITY,PHNO, EMAIL FROM EMP_1 WHERE (YEAR(GETDATE())-YEAR(DOB))>25;

--EID NAM DOJ OF EMPLOYEES WHO HAVE COMPLETED 5 YEAR IN THE COMPANY

SELECT * FROM EMP_1;
SELECT * FROM EMP_SAL;

SELECT EMP_1.EMPID,NAME,DOJ, YEAR(GETDATE())-YEAR(DOJ) AS 'COMPLETED YEARS' FROM EMP_1 INNER JOIN EMP_SAL
ON EMP_1.EMPID=EMP_SAL.EID;

--SAMPLE TRYING
SELECT EMP_1.EMPID,NAME,DOJ, MONTH(GETDATE())-MONTH(DOJ) AS 'COMPLETED MONTHS' FROM EMP_1 INNER JOIN EMP_SAL
ON EMP_1.EMPID=EMP_SAL.EID;

--DETAILS OF MANAGERS HAVING BIRTHDAY IN THE CURRENT MONTH

SELECT * FROM EMP_1 WHERE EMPID IN (SELECT EID FROM EMP_SAL WHERE MONTH(DOB)=MONTH(GETDATE())-1);  --REMOVE  MINUS ONE

-- EID, DEPT, DESI, SALARY OF THE EMPLOYEE WHO IS GETTING THE MAXIMUM SALARY
--FIRST WAY
SELECT EID, DEPT, DESI, SALARY FROM EMP_SAL
WHERE SALARY IN 
(SELECT MAX(SALARY) FROM EMP_SAL);

-- SECOND WAY
SELECT EID, DEPT, DESI, SALARY FROM EMP_SAL
WHERE SALARY IN 
(SELECT TOP 5 SALARY FROM EMP_SAL ORDER BY SALARY DESC);

--EID NAME OF EMPLOYEE WHO HAS LONGEST NAME
SELECT EMPID, NAME, LEN(NAME) AS 'LONGEST NAME LENGTH' FROM EMP_1
WHERE LEN(NAME) IN 
(SELECT MAX(LEN(NAME)) FROM EMP_1);

--ASSIGNMENT 7---
--CREATE A FUNCTION CALC TO PERFORM THE SPECIFIED OPERATION ON THE GIVEN TWO NUMVBRS;
---
















































































































