-- CREATE BELOW PROCEDURES IN THE INVENTORY DATABASE AS SPECIFIED:


CREATE SEQUENCE MYSQ
AS INT
START WITH 1
INCREMENT BY 1;

SELECT NEXT VALUE FOR MYSQ;
DROP SEQUENCE MYSQ;

CREATE FUNCTION GEN_ID(@C AS CHAR(1),@N AS INT)
RETURNS CHAR(5)
AS 
BEGIN
		DECLARE @R AS CHAR(5);
		SELECT @R=CASE	
			WHEN @N<10 THEN CONCAT(@C,'000',@N)
			WHEN @N<100 THEN CONCAT(@C,'00',@N)
			WHEN @N<1000 THEN CONCAT(@C,'0',@N)
			WHEN @N<10000 THEN CONCAT(@C,'',@N)
		END;
		RETURN @R;
END;

DROP FUNCTION GEN_ID;

SELECT DBO.GEN_ID('E',1);

--ADDSUPPLIER- SHOULD ADD THE SUPPLIER IN THE SUPLIER TABLE AND DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED.
USE INVENTORY;

INSERT INTO SUPPLIER VALUES('S0001','ANIL','H. 84 BHARAT NAGAR','DELHI','9915132869','CAPITALLATERA@GMAIL.COM');

SELECT * FROM SUPPLIER;

DROP PROCEDURE ADDSUPPLIER;
CREATE PROCEDURE ADDSUPPLIER (@SNAME VARCHAR(20),@SADD VARCHAR(20), @SCITY VARCHAR(20),@SPHONE VARCHAR(10),@EMAIL VARCHAR(30))
AS BEGIN
		DECLARE @ID AS INT;
		DECLARE @SID AS CHAR(5);
		SET @ID=(NEXT VALUE FOR MYSQ);
		SET @SID=DBO.GEN_ID('S',@ID)

		INSERT INTO SUPPLIER VALUES(@SID,@SNAME,@SADD,@SCITY,@SPHONE,@EMAIL);
		SELECT * FROM SUPPLIER;
END;

ADDSUPPLIER 'ANIL','H. 84 BHARAT NAGAR','DELHI','9915132863','CAPITALLATERA@GMAIL.COM';


DELETE FROM SUPPLIER WHERE SID='8';


--ADDPRO- SHOULD ADD THE PRODUCT IN THE PRODUCT TABLE AND DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED.
CREATE SEQUENCE MYSQ2
AS INT
START WITH 1
INCREMENT BY 1;

DROP PROCEDURE ADDPRO;
CREATE PROCEDURE ADDPRO (@PDESC AS VARCHAR(20),@PRICE AS INT,@CATEGORY AS VARCHAR(20),@SID AS CHAR(5))
AS 
BEGIN
	DECLARE @ID AS INT;
	DECLARE @PID AS CHAR(5);
	SET @ID=NEXT VALUE FOR MYSQ2;
	SET @PID=DBO.GEN_ID('P',@ID)
	INSERT INTO PRODUCT VALUES(@PID,@PDESC,@PRICE,@CATEGORY,@SID)
	SELECT * FROM PRODUCT;
END;

ADDPRO 'MOUSE',800,'IT','S0002';
ADDPRO 'LAPTOP',30000,'IT','S0003'

DELETE FROM PRODUCT WHERE PID='P0004';

--ADDCUST- SHOULD ADD THE CUSTOMER IN THE CUSTOMER TABLE AND DISPLAY THE DETAILS OF THE NEW CUSTOMER ADDED.

CREATE SEQUENCE MYSQ3 
AS INT
START WITH 1
INCREMENT BY 1;

DROP PROCEDURE ADDCUST;
CREATE PROCEDURE ADDCUST (@CNAME AS VARCHAR(20),@ADDRES AS VARCHAR(30),@CITY AS VARCHAR(20),@PHONE AS VARCHAR(10), @EMAIL AS  VARCHAR(30),@DOB AS DATE)
AS 
BEGIN
	DECLARE @ID AS INT;
	DECLARE @CID AS CHAR(5);
	SET @ID=NEXT VALUE FOR MYSQ3;
	SET @CID=DBO.GEN_ID('C',@ID);
	INSERT INTO CUST VALUES(@CID,@CNAME,@ADDRES,@CITY,@PHONE,@EMAIL,@DOB);
	SELECT * FROM CUST;
END;

ADDCUST 'ANIL','H. NO 84 BHARAT NAGAR','JALANDHAR CITY','740977599','CAPITALLATERA@GMAIL.COM','19-NOV-1993';
ADDCUST 'ABHISHEK','AMBIKA COLONY','JALANDHAR CITY','9877105976','ABHISHEKJAH4754@GMAIL.COM','21-JAN-1994'; --DATE WAS AN ISSUE HERE

DELETE FROM CUST WHERE CID='C1';
SELECT * FROM CUST;


--ADDORDER- SHOULD ADD THE ORDER IN THE ORDERS TABLE AND DISPLAY THE DETAILS OF THE ORDER. ORDERDATE SHOULD BE CURRENTDATE AND SHOULD COME AUTOMATICALLY.


--SELECT GETDATE();

CREATE SEQUENCE MYSQ4
AS INT
START WITH 1
INCREMENT BY 1;


DROP PROCEDURE ADDORDER;

CREATE PROCEDURE ADDORDER (@CID AS CHAR(5),@PID AS CHAR(5),@OQTY AS INT)
AS 
BEGIN
	DECLARE @OID AS CHAR(5);
	DECLARE @ODATE AS DATE;
	DECLARE @ID AS INT;
	SET @ID=NEXT VALUE FOR MYSQ4;
	SET @OID=DBO.GEN_ID('O',@ID);
	SET @ODATE=GETDATE()

	INSERT INTO ORDERS VALUES(@OID,@ODATE,@CID,@PID,@OQTY)
	SELECT * FROM ORDERS;
END;

SELECT * FROM CUST;
SELECT * FROM PRODUCT;

ADDORDER 'C0002','P0001',2;
ADDORDER 'C0006','P0002',1;










