USE INVENTORY;

---CREATE A FUNCTION FOR AUTOGENERATION OF 5 CHARACTERS ALPHA NUMERIC ID. IT SHOULD ACCEPT 2 PARAMETERS A CHARACTER AND THE NUMBER AND RETURN THE ID BY CONCATINATING THE CHARACTER, REQUIRED ZEROS AND THE SPECIFIED NUMBER.

DROP SEQUENCE MYSQ_1
CREATE SEQUENCE MYSQ_1
AS INT
START WITH 1
INCREMENT BY 1

--SELECT NEXT VALUE FOR MYSQ_1;

DROP FUNCTION GENID;
CREATE FUNCTION GENID(@C AS CHAR(1), @NO AS INT)
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID AS CHAR(5);
	SELECT @ID =CASE
					WHEN @NO<10 THEN CONCAT(@C,'000',@NO)
					WHEN @NO<100 THEN CONCAT(@C,'00',@NO)
					WHEN @NO<1000 THEN CONCAT(@C,'0',@NO)
					WHEN @NO<10000 THEN CONCAT(@C,'',@NO)
	END;	
	RETURN @ID;
END;

--SELECT DBO.GENID('A',1);

---RECREATE BELOW PROCEDURES IN THE INVENTORY DATABASE AS SPECIFIED (ALL THE IDs SHOULD BE AUTOMATICALLY GENERATED USING ABOVE CREATED FUNCTION AND SEQUENCES):

---ADDSUPPLIER-SHOULD ADD THE SUPPLIER IN THE SUPLIER TABLE AND DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED.

CREATE PROCEDURE ADDSUPLIER (@SNAME AS VARCHAR(20),@SADD AS VARCHAR(20),@SCITY AS VARCHAR(20),@SPHONE AS VARCHAR(10),@EMAIL AS VARCHAR(30))
AS BEGIN
		DECLARE @V AS INT;
		DECLARE @SID AS CHAR(5);
		SET @V=(NEXT VALUE FOR MYSQ_1);
		SET @SID=DBO.GENID('S',@V)
		INSERT INTO SUPPLIER VALUES(@SID,@SNAME,@SADD,@SCITY,@SPHONE,@EMAIL)
		SELECT * FROM SUPPLIER;
END;

ADDSUPLIER 'ABHISHEK KUMAR','AMBIKA COLONY','DELHI','9915132809','ABHISHEKJHA4534@GMAIL.COM'


---ADDPRO-SHOULD ADD THE PRODUCT IN THE PRODUCT TABLE AND DISPLAY THE DETAILS OF THE PRODUCT ADDED.

CREATE SEQUENCE MYSQ_2
AS INT
START WITH 1
INCREMENT BY 1


CREATE PROCEDURE ADDPROD(@PDESC AS VARCHAR(20),@PRICE AS INT, @CATEGORY AS VARCHAR(20),@SID AS CHAR(5))
AS 
BEGIN
		DECLARE @V AS INT;
		DECLARE @PID AS CHAR(5);
		SET @V=(NEXT VALUE FOR MYSQ_2)
		SET @PID=DBO.GENID('P',@V)
		INSERT INTO PRODUCT VALUES(@PID,@PDESC,@PRICE,@CATEGORY,@SID);
		SELECT * FROM PRODUCT;
END;

ADDPROD 'KEYBOARD',1500,'IT','S0004'


---ADDCUST-SHOULD ADD THE PRODUCT IN THE PRODUCT TABLE AND DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED.

CREATE SEQUENCE MYSQ_3
AS INT
START WITH 1
INCREMENT BY 1

CREATE PROCEDURE ADDCUSTM (@CNAME AS VARCHAR(20),@ADDRESS AS VARCHAR(30),@CITY AS VARCHAR(20), @PHONE AS VARCHAR(10),@EMAIL AS VARCHAR(30),@DOB AS DATE)
AS
BEGIN
		DECLARE @V AS INT;
		DECLARE @CID AS CHAR(5);
		SET @V=(NEXT VALUE FOR MYSQ_3);
		SET @CID=DBO.GENID('C',@V)
		INSERT INTO CUST VALUES(@CID,@CNAME,@ADDRESS,@CITY,@PHONE,@EMAIL,@DOB)
		SELECT * FROM CUST;
END;

ADDCUSTM 'RENU','H.NO. 84 BHARAT NAGAR','JALANDHAR CITY','7340977599','TANIYA@GMAIL.COM','19-NOV-1993'


---ADDORDER-SHOULD ADD THE ORDER IN THE ORDERS TABLE AND DISPLAYS OF THE ORDER. ORDER DATE SHOULD BE CURRENT DATE AND SHOULD COME AUTOMATICALLY.
CREATE SEQUENCE MYSQ_4
AS INT
START WITH 1
INCREMENT BY 1


CREATE PROCEDURE ADDORD (@ODATE AS DATE,@CID AS CHAR(5),@PID AS CHAR(5),@OQTY AS INT)
AS
BEGIN
		DECLARE @V AS INT;
		DECLARE @OID AS CHAR(5);
		SET @V=(NEXT VALUE FOR MYSQ_4)
		SET @OID=DBO.GENID('O',@V)
		INSERT INTO ORDERS VALUES(@OID,@ODATE,@CID,@PID,@OQTY)
		SELECT * FROM ORDERS;
END;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;

ADDORD '2020-11-08','C0001','P0003',2 