-- INNER JOIN, LEFT JOIN, CONSTRAINTS, ORDER BY



USE LEARN;

--WHILE CREATION OF TABLE CONSTRAINT  NOT NULL
CREATE TABLE EMP_1 (EID CHAR(5), NAME VARCHAR(10) NOT NULL, ADDR VARCHAR(30), CITY VARCHAR(10) DEFAULT 'DELHI', DOB DATE, PHNO CHAR(15));

INSERT INTO EMP_1 (EID, ADDR, CITY,DOB,PHNO) VALUES('E0001','DWARKA SEC 11','DELHI','10-JAN-199','9899767650');

SELECT * FROM EMP_1;

-- NOT NULL CONSTRAINT
ALTER TABLE EMP_1 ALTER COLUMN NAME VARCHAR(10) NOT NULL;

UPDATE EMP_1 SET NAME='RAMESH'

INSERT INTO EMP_1 VALUES('E0002','MOHIT','DWARKA SEC 12', 'DELHI','10-NOV-1999','7340977599');

-- DEFAULT CONSTRAINT
ALTER TABLE EMP_1 ADD CONSTRAINT DEFCITY DEFAULT 'DELHI' FOR CITY;

INSERT INTO EMP_1(EID,NAME, ADDR,DOB,PHNO) VALUES ('E0003','KAPIL','C2/10 JANAKPURI','14-FEB-1998','9915132869');

INSERT INTO EMP_1 VALUES ('E0004','ROHIT','DLF PHASE 1','GURGAON','25-FEB-2000','7963251478');

ALTER TABLE EMP_1 DROP CONSTRAINT DEFCITY;
--UNIQUE CONSTRAINTS
ALTER TABLE EMP_1 ADD CONSTRAINT R2 UNIQUE (PHNO);

INSERT INTO EMP_1 VALUES ('E005','MONIKA', '456 SECTOR 60', 'NOIDA','03-MAR-1999', '7340977598');

SELECT * FROM EMP_1;

--CHECK CONSTRAINT

ALTER TABLE EMP_1 ADD CONSTRAINT R_DOB CHECK(DOB >'01-JAN-1900') ;

--PRIMARY KEY CONSTRAINT
ALTER TABLE EMP_1 ALTER COLUMN EID CHAR(5) NOT NULL;

ALTER TABLE EMP_1 ADD CONSTRAINT PK_EID PRIMARY KEY (EID);

--FOREGIN KEY CONSTRAINT
CREATE TABLE EMP_SAL 
(EID CHAR(5) REFERENCES EMP_1 (EID),
DEPT VARCHAR(10),
DESI VARCHAR(20),
SALARY INT);

INSERT INTO EMP_SAL VALUES
('E0001','HR','MANAGER',10000);

INSERT INTO EMP_SAL VALUES
('E0002','HR','ASS.MANAGER',15000);

INSERT INTO EMP_SAL VALUES
('E0003','HR','MANAGER',18000);

SELECT * FROM EMP_1;
SELECT *FROM EMP_SAL;

DELETE EMP_SAL;

ALTER TABLE EMP_SAL
ADD CONSTRAINT FK_EID FOREIGN KEY(EID) REFERENCES EMP_1 (EID);

DROP TABLE EMP_SAL;

UPDATE EMP_1 SET EID='E0005' WHERE CITY='NOIDA';

--BETWEEN -RANGE
-- IN - LIST
--LIKE -PATTERN MATCHING
USE LEARN;

SELECT COUNT(*) FROM EMP_1;
SELECT * FROM EMP_1;

--DISTINCT - UNIQUE VALUES OF A FILED
--ORDER BY -SORTING

SELECT *FROM EMP_1 ORDER BY DOB;

SELECT * FROM EMP_1;
SELECT *FROM EMP_SAL;

--INNER JOIN -RETURNS THE COMMON RECORDS

SELECT EMP_1.EID, EMP_1.NAME,EMP_1.CITY,EMP_SAL.DEPT,EMP_SAL.SALARY 
FROM EMP_1 
INNER JOIN EMP_SAL 
ON EMP_1.EID=EMP_SAL.EID;

-- ALIAS NAME
SELECT E1.EID,E1.NAME,E1.CITY,E2.DEPT,E2.SALARY 
FROM EMP_1 E1
INNER JOIN EMP_SAL E2
ON E1.EID=E2.EID;

SELECT EMP_1.EID, NAME,DOB, DEPT,SALARY 
FROM EMP_1
INNER JOIN EMP_SAL
ON EMP_1.EID=EMP_SAL.EID;

--LEFT JOIN
SELECT EMP_1.EID, EMP_1.NAME,EMP_1.CITY,EMP_SAL.DEPT,EMP_SAL.SALARY 
FROM EMP_1 
LEFT JOIN EMP_SAL 
ON EMP_1.EID=EMP_SAL.EID;

CREATE TABLE CJ1(RNO INT,NAME VARCHAR(15));
CREATE TABLE CJ2(RNO INT,NAME VARCHAR(15));

--INSERT INTO CJ1 VALUES(1,'ANIL');
--INSERT INTO CJ1 VALUES(2,'MANOJ');
--INSERT INTO CJ1 VALUES(3,'KAPIL');
